sudo: required
services:
  - docker

before_install:
  - docker build -t jonakola/sample-app-3-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jonakola/sample-app-3-client-test npm test

after_success:
  - docker build -t jonakola/sample-app-3-client ./client
  - docker build -t jonakola/sample-app-3-nginx ./nginx
  - docker build -t jonakola/sample-app-3-server ./server
  - docker build -t jonakola/sample-app-3-worker ./worker
  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push jonakla/sample-app-3-client
  - docker push jonakola/sample-app-3-nginx
  - docker push jonakola/sample-app-3-server
  - docker push jonakola/sample-app-3-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: sample-app-3
  env: SampleApp3-env
  bucket_name: elasticbeanstalk-us-east-2-243172748836
  bucket_path: sample-app-3
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
